config/routes.rb
Rails.application.routes.draw do
  root to: "ibagems#index"
  resources :ibagems do
    resources :picture_uploads, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ibagem.rb
class Ibagem < ApplicationRecord
  has_many_attached :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ibagems_controller.rb
class IbagemsController < ApplicationController
  before_action :set_ibagem, only: %i[ show edit update destroy ]

  # GET /ibagems or /ibagems.json
  def index
    @ibagems = Ibagem.all
  end

  # GET /ibagems/1 or /ibagems/1.json
  def show
  end

  # GET /ibagems/new
  def new
    @ibagem = Ibagem.new
  end

  # GET /ibagems/1/edit
  def edit
  end

  # POST /ibagems or /ibagems.json
  def create
    @ibagem = Ibagem.new(ibagem_params)

    respond_to do |format|
      if @ibagem.save
        format.html { redirect_to ibagem_url(@ibagem), notice: "Ibagem was successfully created." }
        format.json { render :show, status: :created, location: @ibagem }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ibagem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ibagems/1 or /ibagems/1.json
  def update
    respond_to do |format|
      if @ibagem.update(ibagem_params)
        format.html { redirect_to ibagem_url(@ibagem), notice: "Ibagem was successfully updated." }
        format.json { render :show, status: :ok, location: @ibagem }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ibagem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ibagems/1 or /ibagems/1.json
  def destroy
    @ibagem.destroy

    respond_to do |format|
      format.html { redirect_to ibagems_url, notice: "Ibagem was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ibagem
      @ibagem = Ibagem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ibagem_params
      params.require(:ibagem).permit(:name, :description)
    end
end

app/controllers/picture_uploads_controller.rb
class PictureUploadsController < ApplicationController
  def new
    @ibagem = Ibagem.find(params[:ibagem_id])
  end

  def create
    @ibagem = Ibagem.find(params[:ibagem_id])
    @ibagem.pictures.attach(params[:ibagem][:pictures])
    redirect_to ibagem_path(@ibagem)
  end

  def destroy
    @ibagem = Ibagem.find(params[:ibagem_id])
    @ibagem.pictures.find(params[:id]).purge
    redirect_to ibagem_path(@ibagem)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ibagems_helper.rb
module IbagemsHelper
end

app/helpers/picture_uploads_helper.rb
module PictureUploadsHelper
end

app/views/ibagems/_form.html.erb
<%= form_with(model: ibagem) do |form| %>
  <% if ibagem.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ibagem.errors.count, "error") %> prohibited this ibagem from being saved:</h2>

      <ul>
        <% ibagem.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ibagems/_ibagem.html.erb
<div id="<%= dom_id ibagem %>">
  <p>
    <strong>Name:</strong>
    <%= ibagem.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= ibagem.description %>
  </p>

</div>

app/views/ibagems/edit.html.erb
<h1>Editing ibagem</h1>

<%= render "form", ibagem: @ibagem %>

<br>

<div>
  <%= link_to "Show this ibagem", @ibagem %> |
  <%= link_to "Back to ibagems", ibagems_path %>
</div>

app/views/ibagems/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Ibagems</h1>

<div id="ibagems">
  <% @ibagems.each do |ibagem| %>
    <%= render ibagem %>
    <p>
      <%= link_to "Show this ibagem", ibagem %>
    </p>
  <% end %>
</div>

<%= link_to "New ibagem", new_ibagem_path %>

app/views/ibagems/new.html.erb
<h1>New ibagem</h1>

<%= render "form", ibagem: @ibagem %>

<br>

<div>
  <%= link_to "Back to ibagems", ibagems_path %>
</div>

app/views/ibagems/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ibagem %>

<div>
  <%= link_to "Edit this ibagem", edit_ibagem_path(@ibagem) %> |
  <%= link_to "Back to ibagems", ibagems_path %>
  <%= link_to 'Upload Files', new_ibagem_picture_upload_path(@ibagem) %>

  <%= button_to "Destroy this ibagem", @ibagem, method: :delete %>
</div>

<h5>Files</h5>

<ul>
 <% @ibagem.pictures.each do |picture| %>
    <li>
      <%= image_tag url_for(picture), size: "300" %>
      <%= button_to "X", ibagem_picture_upload_path(@ibagem, picture), method: :delete %>
    </li>
 <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MpaIbagens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/picture_uploads/new.html.erb
<h1>Upload for Ibagem <%= @ibagem.name %></h1>

<%= form_with model: @ibagem, url: ibagem_picture_uploads_path(@ibagem),
              method: :post, local: true do |f| %>
  <%= f.file_field :pictures, multiple: true %><br /><br />
  <%= f.submit 'Upload' %>
<% end %>